move template to correct folder
AICoE/meteor pull request #232
Opened 2021-11-30 12:35 UTC by pacospace

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

2021-11-30 12:35 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fmeteor).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/meteor/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2021-11-30 12:39 UTC, tumido requested changes
can you please delete the templates from the old location as well?

2021-11-30 13:27 UTC, pacospace commented
> can you please delete the templates from the old location as well?

I moved them in the new folder, they

> can you please delete the templates from the old location as well?

done, thanks!!

2021-12-01 12:42 UTC, tumido approved these changes
/lgtm
/approve

2021-12-01 12:42 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/meteor/pull/232#pullrequestreview-820205508" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fmeteor).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/meteor/blob/main/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-12-01 12:43 UTC, merged